services:

  yuru-archive:
    build: .

    ports:
      - "8080:8081"

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      COM_YURU_ARCHIVE_UPLOAD_PATH: /data/uploads

    volumes:
      - "C:/Upload:/data/uploads"

    depends_on:
      - db


  db:
    image: postgres:16
    container_name: yuru-db

    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata: